# Nixpacks配置 - Railway部署优化

[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = ['npm install']

[phases.build]
cmds = [
  'cd client && npm install',
  'cd client && npm run build'
]

[start]
cmd = 'node start.js'

[variables]
NODE_ENV = 'production'