# Nixpacks配置 - Railway部署优化

[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = [
  'npm ci --only=production',
  'cd client && npm ci --only=production'
]

[phases.build]
cmds = [
  'cd client && npm run build',
  'mkdir -p server/public',
  'cp -r client/build/* server/public/ 2>/dev/null || true'
]

[start]
cmd = 'npm start'

[variables]
NODE_ENV = 'production'
PORT = '3001'